### ISSUE TITLE
Errors due to bad obj files throw exceptions instead of calling onError

### ISSUE THREAD

**Issue by JakeDluhy** [sohamkamani/three-object-loader#13]
I was expecting that if my obj was bad/corrupted for whatever reason, then onError would be called when attempting to parse it. However that is not the case, it just throws an exception.

I'd be willing to submit a PR for this

**Comment by JakeDluhy** [comment]
Changes in #14. Would be willing to make them again once #12 gets merged in.

**Comment by JakeDluhy** [comment]
@sohamkamani can you release a new `npm` version? And then we can close this out

**Comment by sohamkamani** [comment]
Done 👍 Thanks for the help!

**Comment by JakeDluhy** [comment]
No problem!
