### ISSUE TITLE
Don't commit the dist/ folder

### ISSUE THREAD

**Issue by AndrewRayCode** [sohamkamani/three-object-loader#2]
Git is ideal for source code, not built code. Built code shouldn't have history in git, because the diffs for it don't matter. A built file should be linked to a CDN in the README or similar.

**Comment by sohamkamani** [comment]
This node module is written in ES6, which means that older versions of node (and if browserify is used without an ES6 transpiler) wont be supported.

The entry point of this node module is actually in the `dist` folder, and sadly files which are gitignored cannot be published to npm (as far as I know)

Would love to hear an alternate solution if it's there.
