### ISSUE TITLE
This repo is out of date and no longer neccessary

### ISSUE THREAD

**Issue by looeee** [sohamkamani/three-object-loader#25]
Hello 😁 Just your friendly neighbourhood three.js dev dropping by. 

This repo and the [associated NPM package](https://www.npmjs.com/package/three-obj-loader) are out of date and obsolete, since [the official three.js NPM package](https://www.npmjs.com/package/three) now contains the up to date `OBJLoader`, both as a standard script file and as an ES6 module. 

There are several out of date forks of three.js loaders around, and they frequently cause confusion for new users. Here's [the latest confused person](https://discourse.threejs.org/t/importing-a-collada-model-with-multiple-materials/8003).  Will you help us by removing your outdated loader?

**Comment by benwinding** [comment]
@looeee Well how do I add the OBJLoader in the current THREE.js version then? 

It doesn't seem to be in the type definitions...

![image](https://user-images.githubusercontent.com/11782590/67646305-66a79e00-f97d-11e9-8f2c-1153c31b574e.png)

_Three.d.ts_

**Comment by looeee** [comment]
Assuming you have the npm package 'three' installed:

``` js
import { ObjectLoader } from 'three/examples/jsm/loaders/OBJLoader.js';
```

**Comment by conor909** [comment]
@looeee I get the follwing even tho I see the file in my node_modules folder:
`Attempted import error: 'ObjectLoader' is not exported from 'three/examples/jsm/loaders/OBJLoader.js'.`

**Comment by Mugen87** [comment]
@sohamkamani The `npm` package [three-gltf-loader](https://www.npmjs.com/package/three-gltf-loader) was also deprecated by its author, see https://github.com/johh/three-gltf-loader/issues/9.

Please do the same with this project.

**Comment by sohamkamani** [comment]
This is done

**Comment by looeee** [comment]
@sohamkamani thank you ^_^
