### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by AndrewRayCode** [sohamkamani/three-object-loader#7]
Looks like there were some major changes to the objloader

https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/OBJLoader.js

by the way, I don't think there needs to be any build steps / gulp etc in this project. You can just point the entry file to the source code. This file is really all that's needed: https://github.com/DelvarWorld/three-object-loader/blob/update/source/index.js

**Comment by Jeremboo** [comment]
+1

It could be cool to update the OBJLoader.js :)

**Comment by sohamkamani** [comment]
Hey @DelvarWorld I'm afraid i'm quite out of date with this. I will definitely work on this when I get time. If you have a working solution in the meanwhile, a pull request would be greatly appreciated :)

**Comment by mflux** [comment]
+1 here, am trying to build babelified three.js VR experiments using http://threejs.org/examples/webvr_vive.html as a starting point, requires obj loader, found this as the first google hit and it lacks loader.setPath as a function.

**Comment by TheChuckster** [comment]
Bump

**Comment by sohamkamani** [comment]
Hey all, I have updated the source to the latest version posted by @AndrewRayCode .

**Comment by lukehorvat** [comment]
Could you re-update, please? 😉  [This line](https://github.com/mrdoob/three.js/blob/92af99c/examples/js/loaders/OBJLoader.js#L628) is now different to [yours](https://github.com/sohamkamani/three-object-loader/blob/c341fb1/source/index.js#L713), causing problems in Three.js r87.

**Comment by jeffersoneagley** [comment]
For that matter, multimaterial is now dead.
